"""empty message

Revision ID: d9123ea8cb96
Revises: 7526cdb4e163
Create Date: 2018-11-22 09:29:44.915922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9123ea8cb96'
down_revision = '7526cdb4e163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time_created')
    op.drop_column('pitches', 'time_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time_created', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('time_created', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
